---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-api
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  namespace: cloudman
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      name: {{ template "fullname" . }}
    spec:
      containers:
      - name: consul
        image: consul
        imagePullPolicy: Always
        ports:
        - containerPort: 8500
          name: ui-port
        - containerPort: 8301
          name: serflan
        - containerPort: 8302
          name: serfwan
        - containerPort: 8600
          name: consuldns
        - containerPort: 8300
          name: server
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/cloudman.conf
          subPath: cloudman.conf
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        command:
        - ./run_web.sh
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: cm-api
        ports:
        - containerPort: 8000
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
