apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "cloudman.fullname" . }}-cm-init-config
  labels:
    app: {{ template "cloudman.name" . }}
    chart: {{ template "cloudman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  global_context.yaml: |
    domain: '{{ .Values.global.domain }}'
    influxdb_url: '{{ include "cloudman.influxdb_url_cluster" . }}'
    influxdb_database: '{{ include "cloudman.influxdb_database" . }}'
    influxdb_username: '{{ .Values.influxdb.setDefaultUser.user.username }}'
    influxdb_password: '{{ .Values.influxdb.setDefaultUser.user.password }}'
  projman_config.yaml: |
{{- range $key, $entry := .Values.projman_config -}}
  {{- $key | nindent 4 -}}:
  {{- if (eq $key "projects") -}}
    {{- range $projkey, $projentry := $entry -}}
      {{- $projkey | nindent 6 -}}:
      {{- range $projchildkey, $projchildentry := $projentry -}}
        {{- $projchildkey | nindent 8 -}}:
        {{- if (eq $projchildkey "charts") -}}
          {{- range $chartkey, $chart := $projchildentry -}}
            {{- $chartkey | nindent 10 -}}:
            {{- if $chart.context -}}
              {{- $bare := omit $chart "context" -}}
              {{- $context := (fromYaml (tpl (toYaml $chart.context) $)) -}}
              {{- toYaml (set $bare "context" $context) | trim | nindent 12 -}}
            {{- else -}}
               {{- toYaml $chart | trim | nindent 12 -}}
            {{- end -}}
          {{- end -}}
        {{- else -}}
          {{- toYaml $projentry | nindent 10 -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- else -}}
    {{- toYaml $entry | nindent 6 -}}
  {{- end -}}
{{- end }}
  helmsman_config.yaml: |
{{- range $key, $entry := .Values.helmsman_config -}}
  {{- $key | nindent 4 -}}:
  {{- if (eq $key "charts") -}}
    {{- range $chartkey, $chart := $entry -}}
      {{- $chartkey | nindent 6 -}}:
      {{- if not $chart.tplValues -}}
        {{- toYaml $chart | trim | nindent 8 -}}
      {{- else -}}
        {{- if $chart.values -}}
          {{- $bare := omit $chart "values" "tplValues" -}}
          {{- $concat := merge (fromYaml (tpl (toYaml $chart.tplValues) $)) ($chart.values) -}}
          {{- toYaml (set $bare "values" $concat) | trim | nindent 8 -}}
        {{- else -}}
          {{ tpl (toYaml $chart.tplValues) $ | trim | nindent 8 -}}
        {{- end -}}
      {{- end -}}
    {{- end -}}
  {{- else -}}
    {{- if eq $key "install_templates" -}}
      {{- range $tmplkey, $tmpl := $entry -}}
        {{- $tmplkey | nindent 6 -}}:
        {{- if not $tmpl.tplValues -}}
          {{- if not $tmpl.context -}}
            {{- toYaml $tmpl | trim | nindent 8 -}}
          {{- else -}}
            {{- $bare := omit $tmpl "context" -}}
            {{- $context := (fromYaml (tpl (toYaml $tmpl.context) $)) -}}
            {{- toYaml (set $bare "context" $context) | trim | nindent 8 -}}
          {{- end -}}
        {{- else -}}
          {{- if $tmpl.values -}}
            {{- $bare := omit $tmpl "values" "tplValues" -}}
            {{- $concat := merge (fromYaml (tpl (toYaml $tmpl.tplValues) $)) ($tmpl.values) -}}
            {{- set $bare "values" $concat -}}
            {{- if $tmpl.context -}}
              {{- $barecontext := omit $bare "context" -}}
              {{- $context := (fromYaml (tpl (toYaml $tmpl.context) $)) -}}
              {{- set $barecontext "context" $context -}}
              {{- toYaml $barecontext | trim | nindent 8 -}}
            {{- else -}}
              {{- toYaml $bare | trim | nindent 8 -}}
            {{- end -}}
          {{- else -}}
            {{- $bare := omit $tmpl "tplValues" -}}
            {{- $tplval := (fromYaml (tpl (toYaml $tmpl.tplValues) $)) -}}
            {{- set $bare "tplValues" $tplval -}}
            {{- if $tmpl.context -}}
              {{- $barecontext := omit $bare "context" -}}
              {{- $context := (fromYaml (tpl (toYaml $tmpl.context) $)) -}}
              {{- set $barecontext "context" $context -}}
              {{- toYaml $barecontext | trim | nindent 8 -}}
            {{- else -}}
              {{- toYaml $bare | trim | nindent 8 -}}
            {{- end -}}
          {{- end -}}
        {{- end -}}
      {{- end -}}
    {{- else -}}
      {{- toYaml $entry | nindent 6 -}}
    {{- end -}}
  {{- end -}}
{{- end -}}
