apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: {{ template "cloudman.fullname" . }}-oidc-keycloakclient
  labels:
    app: gvl-sso
spec:
  realmSelector:
    matchLabels:
      app: {{ .Values.global.keycloak.cloudmanClient.realmSelector }}
  client:
    clientId: {{ .Values.global.keycloak.cloudmanClient.clientId }}
    protocol: openid-connect
    enabled: true
    name: Cloudman OIDC
    public: true
    #secret: '{{ randAlphaNum 8 }}-{{ randAlphaNum 4 }}-{{ randAlphaNum 4 }}-{{ randAlphaNum 12 }}'
    redirectUris:
      - '{{ include "cloudman.root_url" . }}/*'
