apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cloudman.fullname" . }}-secret
  labels:
    app: {{ template "cloudman.name" . }}
    chart: {{ template "cloudman.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  cm_initial_cluster_data.yaml: {{ include "cloudman.cluster_config" . | b64enc | quote }}
