apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "cloudman.fullname" . }}-prom-rules
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "cloudman.name" . }}
    chart: {{ template "cloudman.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  groups:
  - name: cloudman-scaling
    rules:
    - alert: ClusterOverUtilized
      annotations:
        message: Cluster has overcommitted CPU resource requests for Pods and cannot tolerate node failure.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubecpuovercommit
      # If CPU request commitment is more than 100% or
      # CPU usage is > 85% for 2m
      expr: |-
        (
        sum(namespace:kube_pod_container_resource_requests_cpu_cores:sum)
          /
        sum(kube_node_status_allocatable_cpu_cores)
          > 1
        )
        or
        (
          (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[2m]))) > 0.85
        )
      for: 3m
      labels:
        severity: warning
    - alert: ClusterOverUtilized
      annotations:
        message: Cluster has overcommitted memory resource requests for Pods and cannot tolerate node failure.
        runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubememovercommit
      # If memory request commitment is more than 100% or
      # memory usage exceeds 80%
      expr: |-
        (
          sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum)
            /
          sum(kube_node_status_allocatable_memory_bytes)
            > 1
        )
        or
        (
          (1 - sum(:node_memory_MemAvailable_bytes:sum)
            /
           sum(kube_node_status_allocatable_memory_bytes))
            > 0.8
        )
      for: 3m
      labels:
        severity: warning
    - alert: ClusterUnderUtilized
      annotations:
        message: Cluster is underutilizing resources (<75% committed)
      # If CPU and memory request commitments < 90%
      # and usage is < 60%
      expr: |-
        (
          sum(namespace:kube_pod_container_resource_requests_cpu_cores:sum)
            /
          sum(kube_node_status_allocatable_cpu_cores)
            < 0.9
        )
        and
        (
          (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[5m]))) < 0.6
        )
        and
        (
          sum(namespace:kube_pod_container_resource_requests_memory_bytes:sum)
            /
          sum(kube_node_status_allocatable_memory_bytes)
            <  0.9
        )
        and
        (
          (1 - sum(:node_memory_MemAvailable_bytes:sum)
            /
           sum(kube_node_status_allocatable_memory_bytes))
            < 0.6
        )
      for: 5m
      labels:
        severity: warning
