# This job will update the keycloak admin user's email and username, since the defaults are empty. Without them,
# Grafana does not allow login
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "cloudman.fullname" . }}-keycloak-update
  labels:
    app: {{ template "cloudman.name" . }}
    chart: {{ template "cloudman.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: post-install-job
        image: "gempesaw/curl-jq"
        command: ["/bin/sh", "/cloudman/update_keycloak_user.sh"]
        volumeMounts:
          - name: cloudman
            mountPath: /cloudman
            readOnly: true
      volumes:
        - name: cloudman   
          configMap:   
            name: {{ template "keycloak_data.name" . }}-realm-data
      restartPolicy: "OnFailure"