kind: ServiceAccount
metadata:
  name: {{ include "cloudman.fullname" . }}-cm-svc-account
  labels:
    app.kubernetes.io/name: {{ template "cloudman.name" . }}
    helm.sh/chart: {{ template "cloudman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "cloudman.fullname" . }}-cm-role-binding
  labels:
    app.kubernetes.io/name: {{ template "cloudman.name" . }}
    helm.sh/chart: {{ template "cloudman.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
subjects:
- kind: ServiceAccount
  name: {{ include "cloudman.fullname" . }}-cm-svc-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
