name: Package
on:
  pull_request:
    types: [closed]
jobs:
  package:
    name: Package and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: msafadieh/helm-ci@master
        with:
          chart-name: projman
          charts-repo: msafadieh/helm-charts
          github-token: ${{ secrets.GITHUB_TOKEN }}
          chart-token: ${{ secrets.CHART_TOKEN }}
          github-context: ${{ toJson(github) }}
          git-branch: ${{ github.event.pull_request.base.ref }}
