dependencies:
  - name: cloudlaunch
    repository: https://raw.githubusercontent.com/CloudVE/helm-charts/master
    version: 0.3.0
  - name: keycloak
    repository: https://codecentric.github.io/helm-charts
    version: 6.0.0
  - name: prometheus-operator
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 8.5.15
    alias: prometheus
  - name: influxdb
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 3.0.2
