dependencies:
  - name: cloudlaunch
    repository: https://raw.githubusercontent.com/CloudVE/helm-charts/master
    version: 0.6.0
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 17.0.2
    alias: kubeprometheus
  - name: influxdb
    repository: https://charts.helm.sh/stable
    version: 3.0.2
