dependencies:
  - name: cloudlaunch
    repository: https://raw.githubusercontent.com/CloudVE/helm-charts/master
    version: 0.4.0
  - name: keycloak
    repository: https://codecentric.github.io/helm-charts
    version: 6.0.0
  - name: kube-prometheus-stack
    repository: https://prometheus-community.github.io/helm-charts
    version: 14.0.1
    alias: prometheus
  - name: influxdb
    repository: https://charts.helm.sh/stable
    version: 3.0.2
