dependencies:
  - name: cloudlaunch
    repository: https://raw.githubusercontent.com/CloudVE/helm-charts/master/
    version: 0.1.0
  - name: keycloak
    repository: https://kubernetes-charts.storage.googleapis.com/
    version: 4.0.1
  - name: prometheus
    repository: https://raw.githubusercontent.com/CloudVE/helm-charts/master/
    version: 6.2.1
