dependencies:
    - name: consul
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 0.3.0
    - name: rabbitmq
      repository: https://kubernetes-charts.storage.googleapis.com/
      version: 0.5.3
