# CloudMan has the same dependencies and structure as cloudlaunch,
# and only differs in the container images.

cloudlaunch:
    nameOverride: cloudman
    container_name: cloudman-ui
    image:
      repository: cloudve/cloudman-ui
      tag: latest

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      path: /
      hosts:
        - cloudman-local
      tls: []

    cloudlaunch-server:
        nameOverride: cloudman
        container_name: cloudman-server
        image:
          repository: cloudve/cloudman-server
          tag: latest
        env_prefix: CLOUDMAN
        celery_app_name: cloudman
        django_settings_module: cloudman.settings
        django_dir: cloudman
        extra_env:
            rancher_url:
            rancher_api_key:
            rancher_cluster_id:
            rancher_project_id:
            rancher_node_command:
            cm_bootstrap_data:
        postgresql:
            enabled: true
            postgresDatabase: cloudman
            postgresUser: cloudman
            postgresPassword: some_pass
