# CloudMan has the same dependencies and structure as cloudlaunch,
# and only differs in the container images.

admin_firstname: "CloudMan"
admin_lastname: "Admin"
admin_email: "cloudman@someplace.org"

projman_config:
  projects:
    - name: gvl

helmsman_config:
  repositories:
     - name: cloudve
       url: https://raw.githubusercontent.com/CloudVE/helm-charts/master/
     - name: jupyterhub
       url: https://jupyterhub.github.io/helm-chart/
  charts:
    - name: stable/kubernetes-dashboard
      namespace: kube-system
      values:
        rbac:
          clusterAdminRole: true
        ingress:
          enabled: true
          hosts:
            - ~
          paths:
            - /dashboard
            - /dashboard/*
        enableInsecureLogin: true
    - name: cloudve/galaxy-cvmfs-csi
      namespace: cvmfs
    - name: cloudve/galaxy
      namespace: gvl
      tplValues:
        config:
          oidc_backends_config.xml: |
            <?xml version="1.0"?>
            <OIDC>
                <provider name="custos">
                    <url>{{.Values.cloudlaunch.cloudlaunchServer.ingress.protocol }}://{{ .Values.global.domain | default (index .Values.cloudlaunch.cloudlaunchServer.ingress.hosts 0) }}/auth</url>
                    <client_id>galaxy-auth</client_id>
                    <client_secret>{{ .Values.galaxy_oidc_client_secret }}</client_secret>
                    <redirect_uri>{{.Values.cloudlaunch.cloudlaunchServer.ingress.protocol }}://{{ .Values.global.domain | default (index .Values.cloudlaunch.cloudlaunchServer.ingress.hosts 0) }}/authnz/custos/callback</redirect_uri>
                    <realm>master</realm>
                </provider>
            </OIDC>
      values:
        config:
          galaxy.yml:
            galaxy:
              enable_oidc: true
              oidc_config_file: /galaxy/server/config/oidc_config.xml
              oidc_backends_config_file: /galaxy/server/config/oidc_backends_config.xml
          oidc_config.xml: |
            <?xml version="1.0"?>
            <OIDC>
                <Setter Property="VERIFY_SSL" Value="False" Type="bool"/>
                <Setter Property="REQUESTS_TIMEOUT" Value="3600" Type="float"/>
                <Setter Property="ID_TOKEN_MAX_AGE" Value="3600" Type="float"/>
            </OIDC>
        persistence:
          storageClass: nfs-provisioner
        postgresql:
          persistence:
            storageClass: ebs-provisioner
        ingress:
          path: /gvl/galaxy

#    version:

# CloudMan bootstrap data
cm_initial_cluster_data:
rancher_url:
rancher_api_key:
rancher_cluster_id:
rancher_project_id:
galaxy_oidc_client_secret:

# Special global values which are accessible from all charts
global:
    domain: 192.168.99.100

cloudlaunch:
  nameOverride: cloudman
  container_name: cloudman-ui
  image:
    repository: cloudve/cloudman-ui
    tag: latest

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
    path: /
    hosts:
      - ~
    tls: []

  cloudlaunchServer:
    nameOverride: cloudman
    container_name: cloudman-server
    image:
      repository: cloudve/cloudman-server
      tag: latest
    env_prefix: CLOUDMAN
    celery_app_name: cloudman
    django_settings_module: cloudman.settings
    django_dir: /app/cloudman
    initial_data: []
    extra_init_scripts:
      load_bootstrap.sh: |
        #!/bin/sh
        /app/venv/bin/python manage.py import_cloud_data /app/secrets/cm_initial_cluster_data.yaml
        /app/venv/bin/python manage.py create_cluster default KUBE_RANCHER /app/secrets/cm_initial_cluster_data.yaml
        /app/venv/bin/python manage.py helmsman_load_config /opt/cloudman/helmsman_config.yaml
        /app/venv/bin/python manage.py projman_load_config /opt/cloudman/projman_config.yaml
    extra_config_mounts:
      - name: cloudman-extra-config
        mount_path: /opt/cloudman/
        config_name: '{{ template "cloudman.fullname" . }}-cm-init-config'
        read_only: true
    extra_secret_mounts:
      - name: cloudman-bootstrap
        mount_path: /app/secrets
        secret_name: '{{ template "cloudman.fullname" . }}-secret'
        read_only: true
    extraVolumes: |
      - name: kubeconfig
        emptyDir: {}
    extraVolumeMounts: |
      - name: kubeconfig
        mountPath: /home/cloudman
    extra_env:
      oidc_enabled: "True"
      oidc_auth_uri: "{{.Values.ingress.protocol }}://{{ .Values.global.domain | default (index .Values.ingress.hosts 0) }}/auth/realms/master"
      oidc_client_id: "cloudman"
      oidc_public_uri: "{{.Values.ingress.protocol }}://{{ .Values.global.domain | default (index .Values.ingress.hosts 0) }}/cloudman"
    postgresql:
      enabled: true
      postgresDatabase: cloudman
      postgresUser: cloudman
      postgresPassword: some_pass
    ingress:
      enabled: true
      path: /cloudman
      hosts:
        - ~
      protocol: https

keycloak:
  keycloak:
    username: admin
    password: changeMe
    ingress:
      enabled: true
      # Add a null host to default to IP
      hosts:
        - ~
      path: /auth
    persistence:
      deployPostgres: false
      dbVendor: H2 
    extraVolumes: |
      - name: realm-data
        configMap:
          name: '{{ template "keycloak_data.name" . }}-realm-data'
      - name: theme
        emptyDir: {}

    extraVolumeMounts: |
      - name: realm-data
        mountPath: "/realm/"
        readOnly: true
      - name: theme
        mountPath: /opt/jboss/keycloak/themes/keycloak

    extraArgs: >
      -Dkeycloak.migration.action=import -Dkeycloak.migration.provider=singleFile
      -Dkeycloak.migration.file=/realm/realm.json -Dkeycloak.migration.strategy=IGNORE_EXISTING

    extraInitContainers: |
      - name: theme-provider
        image: cloudve/gvl-keycloak-theme:latest
        imagePullPolicy: IfNotPresent
        command:
          - sh
        args:
          - -c
          - |
            echo "Copying theme..."
            cp -R /gvltheme/* /theme
            echo "done."
        volumeMounts:
          - name: theme
            mountPath: /theme

prometheus:
  grafana:
    ingress:
      domain: "{{ .Values.global.domain }}"
